name: Xcode

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        # Change to your testing scheme; currently uses first scheme
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
        
        # Device to build for
        export platform="iOS Simulator"
        export name="iPhone Xs"
        
        # Begin Build
        xcodebuild build-for-testing -scheme $scheme -destination "platform=$platform,name=$name"
    - name: Test
      run: |
        # Searches for all schemes ending with "Test"
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'].select{ |i| i.end_with?('Tests') }[0]")
        
        # Device for testing
        # platform="iOS Simulator"
        # name="iPhone Xs"
        
        # Begin Tests
        for s in $scheme; do xcodebuild test-without-building -scheme $scheme -destination "platform=$platform,name=$name"; done;
        
