name: Xcode

on: [push]

jobs:
  build:
  
    name: Build and Test
    runs-on: macOS-latest
    
    steps:
    
    - uses: actions/checkout@v1

      # Finds the first listed scheme
      # Delete this step if you specify a scheme
    - name: Get Default Scheme
      if: matrix.scheme == 'default'
      run: |
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
        echo $default | cat >default
        echo Using default scheme: $default
    
    - name: Build and Test
      env:
        scheme: default
        platform: iOS Simulator
        device: iPhone Xs
      run: |
        if [ $scheme = default ]; then scheme=$(cat default); fi
        xcodebuild build-for-testing -scheme $scheme -destination "platform=$platform,name=$device"
        xcodebuild test-without-building -scheme $scheme -destination "platform=$platform,name=$device"
        
