name: Xcode

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        # Change to your testing scheme; currently uses first scheme
        scheme=$(xcodebuild -list -json | tr -d "\n" | ruby -e "require 'rubygems';require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
        xcodebuild build-for-testing -scheme $scheme CODE_SIGN_ENTITY="" CODE_SIGNING_REQUIRED=NO
    - name: Test
      run: |
        # Change to your testing scheme; this currently searches for the first scheme name containing "Test"
        scheme=$(xcodebuild -list -json | tr -d "\n" | ruby -e "require 'rubygems';require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][1]")
        # Device for testing
        platform="iOS Simulator"
        name="iPhone Xs"
        # Begin Test
        xcodebuild test -scheme $scheme -destination "platform=$platform,name=$name"
